//
//  GTCDialogsStrings.h
//  Pods
//
//  Created by liuxc on 2018/10/11.
//

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM: components/Dialogs/src/MaterialDialogs.bundle/Resources/en.lproj/MaterialDialogs.strings
// GENERATED BY: generate_string_tables.py

typedef enum {
    kStr_GTCDialogsPresentedAccessibilityAnnouncement = 0,
} GTCDialogsStringId;
