//
//  GTCDialogsStrings_table.h
//  Pods
//
//  Created by liuxc on 2018/10/11.
//

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM: components/Dialogs/src/MaterialDialogs.bundle/Resources/en.lproj/MaterialDialogs.strings
// GENERATED BY: generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kMaterialDialogsStringTable[] = {
    @"GTCDialogsPresentedAccessibilityAnnouncement",   // Alert
};
#define kNumGTCDialogsStrings 1
#define kGTCDialogsStringsOffset 0
#define kGTCDialogsStringsEnd 10000
static NSString *const kGTCDialogsStringsTableName = @"GTCDialogs";
