//
//  GTAppBarStrings_table.h
//  Pods
//
//  Created by liuxc on 2018/8/22.
//

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/AppBar/src/GTAppBar.bundle/Resources/en.lproj/GTAppBar.strings
// GENERATED BY: generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kGTAppBarStringTable[] = {
    @"GTAppBarBackButtonAccessibilityLabel",   // Back
};
#define kNumGTAppBarStrings 1
#define kGTAppBarStringsOffset 0
#define kGTAppBarStringsEnd 10000
static NSString *const kGTAppBarStringsTableName = @"GTAppBar";

