//
//  GTPageControlStrings.h
//  Pods
//
//  Created by liuxc on 2018/8/27.
//

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/PageControl/src/GTPageControl.bundle/Resources/en.lproj/GTPageControl.strings
// GENERATED BY: generate_string_tables.py

typedef enum {
    kStr_GTPageControlAccessibilityLabel = 0,
} GTPageControlStringId;
