//
//  GTPageControlStrings_table.h
//  Pods
//
//  Created by liuxc on 2018/8/27.
//

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/PageControl/src/MaterialPageControl.bundle/Resources/en.lproj/MaterialPageControl.strings
// GENERATED BY: generate_string_tables.py

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kGTPageControlStringTable[] = {
    @"GTPageControlAccessibilityLabel",  // page %1$zd of %2$zd
};
#define kNumGTControlStringsOffset 0
#define kGTPageControlStringsEnd 10000
static NSString *const kGTPageControlStringsTableName = @"GTPageControl";
