workspace 'Catalog.xcworkspace'

target 'Catalog' do
  platform :ios, '8.0'
  project 'Catalog.xcodeproj'
  use_frameworks!
  pod 'GTCatalog'
  pod 'GTComponentsExamples', :path => '../'
  pod 'GTKitComponents', :path => '../'
end

target "GTCDragons" do
    platform :ios, '8.0'
    project 'Catalog.xcodeproj'
    use_frameworks!
    pod 'GTCatalog'
    pod 'GTComponentsExamples', :path => '../'
    pod 'GTKitComponents', :path => '../'
end
  
target "UnitTests" do
  platform :ios, '8.0'
  pod 'GTCatalog'
  pod 'GTComponentsUnitTests', :path => '../'

  use_frameworks! 
end
