//
//  GTFeatureHighlightStrings_table.h
//  Pods
//
//  Created by liuxc on 2018/10/17.
//

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/FeatureHighlight/src/MaterialFeatureHighlight.bundle/Resources/en.lproj/MaterialFeatureHighlight.strings
// GENERATED BY: generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kGTFeatureHighlightStringTable[] = {
    @"GTFeatureHighlightDismissAccessibilityHint",  // Double-tap to dismiss.
};
#define kNumGTFeatureHighlightStrings 1
#define kGTFeatureHighlightStringsOffset 0
#define kGTFeatureHighlightStringsEnd 10000
static NSString *const kGTFeatureHighlightStringsTableName = @"GTFeatureHighlight";
