//
//  GTFeatureHighlightStrings.h
//  Pods
//
//  Created by liuxc on 2018/10/17.
//

// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/FeatureHighlight/src/GTFeatureHighlight.bundle/Resources/en.lproj/GTFeatureHighlight.strings
// GENERATED BY: generate_string_tables.py

typedef enum {
    kStr_GTFeatureHighlightDismissAccessibilityHint = 0,
} GTFeatureHighlightStringId;
