// GENERATED CODE: DO NOT EDIT BY HAND
// GENERATED FROM:
// components/ActivityIndicator/src/GTActivityIndicator.bundle/Resources/en.lproj/MaterialActivityIndicator.strings
// GENERATED BY: generate_string_tables.py

#import <Foundation/Foundation.h>

// A table of string keys to look-up localized strings in the bundle.
// This table is to be indexed using the generated enum.

static NSString *const kGTActivityIndicatorStringTable[] = {
    @"GTActivityIndicatorInProgressAccessibilityValue",   // In Progress
    @"GTActivityIndicatorAccessibilityLabel",   // Activity Indicator
    @"GTActivityIndicatorProgressHaltedAccessibilityValue",   // Progress Halted
    @"GTActivityIndicatorProgressCompletedAccessibilityValue",   // %ld Percent Complete
};
#define kNumGTActivityIndicatorStrings 4
#define kGTActivityIndicatorStringsOffset 0
#define kGTActivityIndicatorStringsEnd 10000
static NSString *const kGTActivityIndicatorStringsTableName = @"GTActivityIndicator";
