//
//  GTCShapedView.h
//  GTCatalog
//
//  Created by liuxc on 2018/8/17.
//

#import <UIKit/UIKit.h>

#import "GTShadowElevations.h"

@protocol GTCShapeGenerating;

/**
 GTCShapedView is a primitive view class which makes it easy to style the shape
 of the view's edges and corners.

 GTCShapedView manages mapping the paths generated by the shapeGenerator to the
 backing CAShapeLayer whenever the view is resized.
 */
@interface GTCShapedView : UIView

/**
 The elevation of the layer in points.

 The higher the elevation, the more spread out the shadow is. This is distinct from the layer's
 zPosition which can be used to order overlapping layers, but will have no affect on the size of
 the shadow.

 Negative values act as if zero were specified.
 */
@property(nonatomic, assign) GTCShadowElevation elevation;

/**
 The shape generator used to generate a new CGPath whenever the view is resized.
 */
@property(nonatomic, strong, nullable) IBOutlet id<GTCShapeGenerating> shapeGenerator;

/**
 Initializes an GTCShapedView.

 @param frame The frame of the shaped view.
 @param shapeGenerator The shape generator used to set the shape of the view.
 */
- (nonnull instancetype)initWithFrame:(CGRect)frame
                       shapeGenerator:(nullable id<GTCShapeGenerating>)shapeGenerator
NS_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame;
- (nullable instancetype)initWithCoder:(nullable NSCoder *)aDecoder NS_DESIGNATED_INITIALIZER;

@end

